function go(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button[data-v]').forEach(b=>b.classList.toggle('active',b.dataset.v===id));if(id==='home')renderHome();if(id==='library')renderLibrary();if(id==='stats')renderStats();if(id==='references')renderRefs();window.scrollTo({top:0,behavior:'smooth'})}
function reward(skill,x=15){state.xp+=x;state.skills[skill]=Math.min(5,(state.skills[skill]||1)+.15);save()}
function miss(m){state.hearts=Math.max(0,state.hearts-1);state.mistakes[m]=(state.mistakes[m]||0)+1;save()}
function startMixed(){const choices=['startQuick','startData','startInvestigation','startDecision','startRequirements','startRelease','startApi'];window[choices[Math.floor(rng()*choices.length)]]()}
function startQuick(){qi=0;selected=null;go('quick');renderQuick()}
function renderQuick(){const z=quickSet[qi];document.getElementById('quickProgress').textContent=`${qi+1} / ${quickSet.length}`;document.getElementById('quickSkill').textContent=z.skill;document.getElementById('quickScenario').textContent=z.s;document.getElementById('quickQ').textContent=z.q;document.getElementById('quickChoices').innerHTML=z.a.map((a,i)=>`<button class="choice" onclick="selectQuick(${i})">${String.fromCharCode(65+i)}. ${a}</button>`).join('');document.getElementById('quickFeedback').className='feedback';document.getElementById('quickCheck').style.display='inline-block';document.getElementById('quickCheck').disabled=true;document.getElementById('quickNext').style.display='none';selected=null}
function selectQuick(i){selected=i;document.querySelectorAll('#quickChoices .choice').forEach((b,j)=>b.classList.toggle('sel',j===i));document.getElementById('quickCheck').disabled=false}
function checkQuick(){const z=quickSet[qi],good=selected===z.c;document.querySelectorAll('#quickChoices .choice').forEach((b,j)=>{b.classList.remove('sel');if(j===z.c)b.classList.add('good');if(j===selected&&!good)b.classList.add('bad')});const f=document.getElementById('quickFeedback');f.className='feedback show';f.innerHTML=`<strong>${good?'✓ Strong read':'Heart lost'}</strong><p>${z.why}</p>`;if(good)reward(z.skill,15);else miss(z.m);document.getElementById('quickCheck').style.display='none';document.getElementById('quickNext').style.display='inline-block';document.getElementById('quickNext').textContent=qi===quickSet.length-1?'Finish':'Next'}
function nextQuick(){qi++;if(qi>=quickSet.length)go('stats');else renderQuick()}
function startData(){go('data');currentData=dataTemplates[Math.floor(rng()*dataTemplates.length)]();renderData()}
function renderData(){const d=currentData;document.getElementById('dataCard').innerHTML=`<div class="eyebrow">${d.title}</div><div class="scenario">${d.scenario}</div><div class="datawrap"><table class="datatable"><thead><tr>${d.headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${d.rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="prompt"><label>${d.calc}</label><input id="dataCalc" class="field" type="number" step="0.1" placeholder="Your calculation"><span class="tiny"> ${d.unit}</span></div><div class="prompt"><label>${d.written}</label><textarea id="dataWritten" placeholder="State what the data suggests, what it does not prove, and what you would do next."></textarea></div><button class="btn" onclick="checkData()">Submit</button><div class="feedback" id="dataFeedback"></div>`}
function checkData(){const d=currentData,v=parseFloat(document.getElementById('dataCalc').value),text=document.getElementById('dataWritten').value.trim(),tol=Math.max(.15,Math.abs(d.ans)*.012),good=Number.isFinite(v)&&Math.abs(v-d.ans)<=tol;const f=document.getElementById('dataFeedback');f.className='feedback show';f.innerHTML=`<strong>${good?'✓ Calculation checks out':'Check the calculation'}</strong><p>Expected: <b>${d.ans}${d.unit}</b>.</p><p>${d.debrief}</p>${text.length<40?'<p>Your written recommendation is very short. Force yourself to name the signal, uncertainty and next evidence.</p>':''}`;if(good&&text.length>=40)reward('Analytics',25);else if(!good)miss('Making a data conclusion without getting the denominator/calculation right.')}
function startInvestigation(){go('investigate');inv=investigationTemplates[Math.floor(rng()*investigationTemplates.length)];invPicks=[];renderInvestigation()}
function renderInvestigation(){document.getElementById('investigateBudget').textContent=`Evidence picks ${invPicks.length}/3`;document.getElementById('investigateCard').innerHTML=`<div class="eyebrow">Investigation</div><div class="q">${inv.title}</div><div class="scenario">${inv.scenario}</div><p class="sub">You may inspect only three signals before committing to a working hypothesis.</p><div class="evidence">${inv.e.map((e,i)=>`<button class="${invPicks.includes(i)?'sel':''}" onclick="pickEvidence(${i})"><b>${e[0]}</b><span>${invPicks.includes(i)?e[1]:'Tap to inspect'}</span></button>`).join('')}</div><div class="prompt"><label>Working hypothesis</label><textarea id="invHyp" placeholder="What do you currently think is happening, and how confident are you?"></textarea></div><div class="prompt"><label>Next action</label><textarea id="invNext" placeholder="What would you do next, and who needs to be involved?"></textarea></div><button class="btn" onclick="finishInvestigation()">Commit</button><div class="feedback" id="invFeedback"></div>`}