function finishApi(){const groups=[...document.querySelectorAll('#apiCard .choices')],good=groups.filter(g=>g.querySelector('.good')).length,text=document.getElementById('apiWritten').value.trim();const f=document.getElementById('apiFeedback');f.className='feedback show';f.innerHTML=`<strong>${good}/2 checks correct</strong><p>A useful integration brief covers required inputs, authentication, response shape/IDs, error semantics, rate limits, freshness, latency, retries, staging vs production, monitoring and what the rider should see when the dependency fails.</p>`;if(good===2&&text.length>=80)reward('Systems',30);else miss('Treating an API endpoint as sufficient integration definition.')}
let deckFilter='All';
function startFlashcards(){go('flash');const sel=document.getElementById('deckFilter');if(!sel.options.length){const cats=['All',...new Set(flashcards.map(c=>c[0]))];sel.innerHTML=cats.map(c=>`<option>${c}</option>`).join('')}setDeck()}
function setDeck(){deckFilter=document.getElementById('deckFilter').value||'All';deck=flashcards.filter(c=>deckFilter==='All'||c[0]===deckFilter);di=0;renderCard()}
function renderCard(){if(!deck.length)return;const c=deck[di];document.getElementById('deckProgress').textContent=`${di+1} / ${deck.length} · ${c[0]}`;const el=document.getElementById('flashcard');el.className='card flashcard';el.innerHTML=`<div class="front">${c[1]}</div><div class="hint">Tap to reveal</div><div class="back"><div class="definition">${c[2]}</div><div class="why">${c[3]}</div><div class="example"><b>Example</b><br>${c[4]}</div></div>`}
function flipCard(){document.getElementById('flashcard').classList.toggle('flipped')}
function nextCard(){di=(di+1)%deck.length;renderCard()}function prevCard(){di=(di-1+deck.length)%deck.length;renderCard()}
function shuffleDeck(){deck=shuffleSeeded(deck.slice());di=0;renderCard()}
function markCard(got){const key=deck[di][1];state.known[key]=(state.known[key]||0)+(got?1:-1);if(got){state.xp+=2}else state.mistakes[`Review: ${key}`]=(state.mistakes[`Review: ${key}`]||0)+1;save();nextCard()}
function renderStats(){document.getElementById('mastery').innerHTML='<div class="eyebrow">Mastery</div><h2>Skill ratings</h2>'+skills.map(s=>`<div class="row"><span>${s[1]}</span><div class="bar"><i style="width:${Math.min(100,state.skills[s[1]]*20)}%"></i></div><span>${Number(state.skills[s[1]]).toFixed(1)}</span></div>`).join('');const e=Object.entries(state.mistakes).sort((a,b)=>b[1]-a[1]).slice(0,10);document.getElementById('mistakes').innerHTML=e.length?e.map(([m,n])=>`<div class="mistake"><strong>${m}</strong><p>Seen ${n} time${n===1?'':'s'}.</p></div>`).join(''):'<div class="mistake"><strong>Nothing here yet.</strong><p>Patterns you miss will collect here.</p></div>'}
function resetAll(){if(confirm('Reset XP, hearts, mastery, cards and replay deck?')){localStorage.removeItem('fieldwork_game_v3');localStorage.removeItem('fieldwork_game');location.reload()}}
ensureCycle();renderHome();renderLibrary();renderRefs();renderStats();chrome();setInterval(updateRefresh,60000);