const flashcards_part5=[
['Ecosystem','GO','Transit’s step-by-step navigation mode; it also supports crowdsourced real-time location data from riders.','The rider is not only consuming information but can contribute data back into the system.','GO riders help fill gaps where agency real-time is weak.'],
['Ecosystem','Rate-My-Ride','Transit’s in-trip intercept surveying system that asks contextually timed questions about stops, vehicles and trips.','It turns rider experience into structured, localizable evidence for agencies.','Responses can be tagged to stop, vehicle, route and time of day while remaining anonymous.'],
['Ecosystem','Transit Terminal','Agency-facing tools including service-alert publishing and usage information.','The agency operator experience and downstream rider effect both matter.','Choosing “No Service” can change how affected service appears and routes in the app.'],
['Ecosystem','ETA Accuracy Benchmark','A shared approach for evaluating whether predictions are accurate relative to actual arrival, with tighter expectations as arrival nears.','Accuracy is not a vibe; it can be measured consistently and compared.','Evaluate predictions at different time horizons against actual arrival.'],
['Ecosystem','Ghost bus','A predicted/scheduled bus appears to be coming but no vehicle actually arrives.','It damages trust and can have many causes across operations, data and prediction layers.','A trip remains visible after it was cancelled operationally.'],
['Ecosystem','Surprise / bonus bus','A vehicle arrives even though no real-time prediction indicated it would.','Real-time quality includes missing coverage, not only false positives.','A bus arrives with no ETA shown.'],
['Ecosystem','Jitter','Predictions fluctuate up and down instead of converging smoothly.','Even if the final prediction is technically accurate, unstable ETAs create poor rider decisions.','ETA jumps 4→9→3 minutes.'],
['Ecosystem','Real-time coverage','The share of relevant trips/vehicles for which usable real-time information exists.','High accuracy on a small covered subset can still be a bad rider experience.','95% accurate predictions but only 55% of trips have predictions.'],
['Ecosystem','Life beyond cars','Transit’s vision is to help people make the most of bus, train, bike and walking so they do not need to own a car.','Product tradeoffs should ultimately connect to making sustainable transportation easier and more joyful to use.','A feature that makes transit easier to understand can support mode shift even if it is not flashy.'],
['Ecosystem','“Je ne sais quoi” / craft','Transit’s manifesto explicitly values the extra effort in performance, wording, design and animation that makes the product uplifting.','Quality is not only functional correctness; simplicity and delight are part of the product standard.','Shaving latency, choosing clearer copy or refining a small interaction can matter.'],
['Ecosystem','Transparency','Transit’s manifesto says teammates should be kept in the loop and hard questions deserve straight answers.','Expectation management benefits from explicit uncertainty and honest tradeoffs.','Say what is known, unknown, blocked and when the next decision will happen.'],
['Ecosystem','Partnership mindset','Transit explicitly says it cannot do the work alone and partners with agencies, cities, research groups and others.','Agency feedback is not merely “customer requests”; partner relationships are part of how the product and broader transit ecosystem improve.','An agency and Transit co-develop a standardized way to communicate detours.'],
['Ecosystem','Privacy by design','Transit says it separates app usage from personal data and generalizes location information in agency insights.','Analytics and rider feedback should answer operational questions without unnecessarily identifying individuals.','Rate-My-Ride responses shared with agencies are anonymous.'],
['Ecosystem','Open mobility','The principle that transit and mobility data should be available through open standards/APIs so riders can use many tools and modes.','Product decisions can improve the whole ecosystem, not only one app.','Detour data standardized through GTFS-realtime can be reused by agencies and other apps.'],
['Ecosystem','Multimodal trip','A journey combining more than one mode or operator, such as bus + walk + bikeshare or transit + on-demand.','The rider’s job is getting from A to B, not interacting with one agency in isolation.','A first-mile on-demand ride connects to a fixed-route bus.'],
['Ecosystem','Localization','Adapting product behaviour, copy, data or rules to legitimate local context.','Transit operates across cities with different languages, fares, service patterns and infrastructure.','A local fare rule needs configuration without changing every city.'],
['Ecosystem','Accessibility / step-free routing','Trip planning that accounts for whether a rider can use stairs and whether accessible paths/elevators are available.','Accessibility constraints can change whether a trip is possible, not just how it is described.','An elevator outage invalidates an otherwise optimal rail itinerary for a step-free rider.']
];