const flashcards_part1=[
['Operations','AVL','Automatic Vehicle Location. Technology/data used to determine vehicle locations, often via GPS.','It is a common source for real-time vehicle tracking.','If AVL stops transmitting, vehicle positions may go stale.'],
['Operations','CAD/AVL','Computer-Aided Dispatch / Automatic Vehicle Location. Operational systems combining dispatch/control with vehicle location.','Service changes may exist operationally before they are reflected in rider-facing feeds.','Dispatch cancels a run but downstream passenger information is not updated.'],
['Operations','APC','Automatic Passenger Counter. Hardware/system that estimates boardings, alightings or onboard load.','Crowding data quality can affect rider information and analytics.','Rider feedback reveals an APC calibration problem.'],
['Operations','OTP','On-time performance: a service reliability measure comparing actual performance with a defined schedule threshold. Context can also use OTP for OpenTripPlanner, so ask.','Transit acronyms can be overloaded; always establish context.','“OTP dropped” in an agency performance review likely means on-time performance.'],
['Operations','Dwell time','Time a vehicle spends stopped while riders board/alight and operations occur.','Dwell affects travel time and reliability.','Wheelchair boarding or heavy passenger loads can increase dwell at a stop.'],
['Operations','Layover / recovery time','Scheduled time at a terminal or endpoint that allows operators to rest and service to recover from delay.','Removing too much recovery can create cascading lateness.','A late bus reaches the terminal and uses recovery time before its next trip.'],
['Operations','Deadhead','Vehicle movement while not carrying passengers, often between depot and service or between assignments.','Operational movements may appear in source systems but should not be treated as passenger service.','A bus travels from the garage to the first stop.'],
['Operations','Block','A sequence of vehicle trips assigned to one vehicle over part or all of a service day.','Problems can propagate across trips that share the same vehicle work.','A late inbound trip affects the next trip on the same block.'],
['Operations','Run','An operator work assignment, often covering pieces of vehicle service during a shift.','Crew availability and operating assignments can influence whether scheduled service actually runs.','A missed operator assignment causes a cancelled trip.'],
['Operations','Pass-up','A vehicle passes waiting riders without boarding them, often because it is full or cannot safely take more passengers.','Rider feedback can reveal capacity problems that schedules alone do not show.','Rate-My-Ride responses identify frequent pass-ups at one stop.'],
['Operations','Interlining','A vehicle continues from one route/service into another without returning to a depot.','Delays and changes can cross route boundaries.','A late Route A trip becomes Route B at the terminal.'],
['Operations','Timepoint','A designated stop/location used for schedule control or published timing.','Not every stop necessarily has the same scheduling significance.','Operators may be instructed not to depart a timepoint early.'],
];