const flashcards_part3=[
['Product & delivery','Acceptance criteria','Specific testable conditions that must be true for work to be accepted.','They translate intent into something Engineering, QA and stakeholders can verify.','Given a severe alert, affected routes are removed from trip planning and the correct message appears.'],
['Product & delivery','Functional requirement','What the system should do.','It describes behaviour rather than quality attributes.','A user can target an alert to a route and stop.'],
['Product & delivery','Non-functional requirement','A quality/constraint such as performance, reliability, accessibility, security, privacy or localization.','Many critical launch failures live outside the happy-path feature behaviour.','The dashboard must meet accessibility requirements and load within an acceptable latency budget.'],
['Product & delivery','Definition of Done','A shared standard for when work is complete, often including testing, documentation, instrumentation and release readiness expectations.','It prevents “code merged” from masquerading as finished product work.','A story is not done until analytics and QA are complete.'],
['Product & delivery','UAT','User Acceptance Testing. Validation by business/customer users that a solution works for intended real-world use.','UAT catches mismatches between technically correct software and operational reality.','Agency staff test the tool with realistic alerts before launch.'],
['Product & delivery','Staging','A pre-production environment used to test integrated behaviour before release.','A bug can exist only in production because data/configuration differs, so environment matters.','A feed works in staging but a production credential is wrong.'],
['Product & delivery','Feature flag','A control that allows functionality to be enabled or disabled without a new code deployment.','Flags enable phased rollout, testing and quick rollback.','Enable a new tool for three pilot agencies first.'],
['Product & delivery','Requirements traceability','Keeping a connection from problem/evidence → requirement → implementation/test → outcome.','It helps explain why something exists and whether the shipped behaviour solves the original need.','An acceptance criterion maps back to a rider/agency problem and later to a success metric.'],
['Product & delivery','Dependency','Something outside the immediate work that must happen or remain available for success.','Dependencies are common sources of schedule risk.','Launch depends on the agency publishing a valid feed and a vendor providing production credentials.'],
['Product & delivery','Technical debt','The future cost created by shortcuts, outdated architecture or deferred cleanup.','A quick agency-specific patch can create permanent maintenance cost.','A one-off branch for one city makes every future release harder to test.'],
];