quickBank.forEach(q=>{if(q.why)q.why=q.why.replace('429 is Too Many Requests. A PO should understand quota, retry behaviour and whether usage fits the contract.','429 is Too Many Requests. Quota, retry behaviour and whether usage fits the contract belong in the investigation.')});

// Content constitution: controls recurrence and technical depth without turning the UI into a study guide.
const FIELDWORK_PROFILE={dimensions:{coding:1,apiArchitecture:2,analytics:3.5,softwareSystems:4,troubleshooting:4,technicalCommunication:4,productManagement:5,agencyStakeholders:5}};
function quickContentWeight(q){const text=((q.s||'')+' '+(q.q||'')).toLowerCase();if(/\b(api|http|json|endpoint|429|rate limit|query parameter|authentication)\b/.test(text))return 2;if(q.skill==='Analytics')return 3.5;if(q.skill==='Systems')return 4;if(q.skill==='Communication')return 4;if(q.skill==='Partner work')return 5;if(q.skill==='Problem framing'||q.skill==='Judgment'||q.skill==='Delivery')return 5;if(q.skill==='Transit domain')return 4;return 3}
function weightedSampleWithoutReplacement(items,count,weightFn,r){return items.map(item=>{const w=Math.max(.1,Number(weightFn(item))||1);return{item,key:-Math.log(Math.max(1e-9,r()))/w}}).sort((a,b)=>a.key-b.key).slice(0,count).map(x=>x.item)}
function weightedQuickSet(bank,count,r){return weightedSampleWithoutReplacement(bank,count,quickContentWeight,r)}
const MIXED_MODE_WEIGHTS=[['startQuick',5],['startDecision',5],['startRequirements',5],['startInvestigation',4],['startRelease',4],['startData',3.5],['startApi',2]];
function weightedModeName(r){const total=MIXED_MODE_WEIGHTS.reduce((s,x)=>s+x[1],0);let n=r()*total;for(const[name,w]of MIXED_MODE_WEIGHTS){n-=w;if(n<=0)return name}return'startQuick'}
function interviewContentWeight(level,q){const t=(q.q+' '+(q.follow||[]).join(' ')).toLowerCase();let w=3;if(/agency|partner|stakeholder|customer|contract|kickoff|expect/.test(t))w=Math.max(w,5);if(/priorit|tradeoff|scope|requirement|roadmap|launch|product|decision|rider/.test(t))w=Math.max(w,5);if(/bug|failure|wrong|reproduce|integration|feed|real-time|system|dependency|staging|production/.test(t))w=Math.max(w,4);if(/engineering|developer|data analyst|design|qa|cross-functional|explain/.test(t))w=Math.max(w,4);if(/metric|analytics|sample|funnel|adoption|satisfaction|data/.test(t))w=Math.max(w,3.5);if(/api|json|http|endpoint/.test(t))w=Math.min(w,2.5);return w}
function weightedInterviewSet(level,r){return weightedSampleWithoutReplacement(level.questions,level.count,q=>interviewContentWeight(level,q),r)}

// Higher-value system, troubleshooting and technical-communication scenarios.
quickBank.push(
{skill:'Systems',s:'Riders in one city report that arrival times freeze for several minutes, then suddenly jump forward. Other cities look normal.',q:'What is the strongest first technical/product framing?',a:['Assume the prediction algorithm is globally broken','Compare the affected city’s incoming real-time freshness and processing timestamps with a healthy city before narrowing the fault','Ask Engineering to rewrite the frontend timer','Wait for more App Store reviews'],c:1,why:'A city-specific failure is a useful discriminator. Trace freshness through the system before blaming a shared prediction or UI layer.',m:'Skipping system localization when narrowing a failure.'},
{skill:'Communication',s:'Engineering says, “We cannot reproduce the bug.” You have three rider complaints.',q:'What is most useful to send back?',a:['A higher priority label','Exact examples with route/trip/stop/time, expected vs actual behaviour, screenshots, device/app context and how often it occurred','A proposed code fix','A request to keep trying'],c:1,why:'Improve the evidence and reproduction surface rather than prescribing implementation.',m:'Escalating a bug without improving reproducibility.'},
{skill:'Communication',s:'A data analyst asks what you mean by “feature adoption.”',q:'What should you clarify before asking for a chart?',a:['The colour of the chart','Who is eligible, the activation/value event, denominator, timeframe, expected cadence and useful segments','Whether the SQL query is hard','Which executive wants the answer'],c:1,why:'A precise product question lets Data choose the right analysis. “Adoption” is not self-defining.',m:'Asking Data for a metric without defining the behaviour.'},
{skill:'Systems',s:'A third-party real-time feed is intermittently stale, but not fully down.',q:'Which product question matters alongside the technical fix?',a:['Which programming language the feed uses','What riders should see when freshness crosses an unacceptable threshold, and how the system recovers when data becomes healthy again','Whether the agency has a logo','Whether the bug can be renamed'],c:1,why:'Degraded dependencies need defined user behaviour, thresholds, monitoring and recovery, not just an engineering incident.',m:'Treating dependency degradation as only an infrastructure problem.'},
{skill:'Delivery',s:'Engineering proposes two implementations. Option A ships faster but creates manual maintenance for every new agency. Option B takes longer but is configurable.',q:'What is the most useful contribution to the decision?',a:['Choose the faster option automatically','Compare immediate need, expected partner scale, ongoing operational cost, risk and reversibility before deciding','Ask Engineering to choose without product context','Choose the more technically elegant option'],c:1,why:'Implementation tradeoffs become product tradeoffs when they change speed, scale, maintenance and future constraints.',m:'Ignoring lifecycle cost when evaluating technical options.'},
{skill:'Systems',s:'The schedule feed is current and Trip Updates show the correct cancellation, but the app still shows the trip as operating.',q:'Where should the investigation move next?',a:['Agency scheduling','Transit ingestion/processing and product presentation of the valid cancellation','Vehicle hardware','Procurement'],c:1,why:'Once upstream evidence is valid, move downstream. Good troubleshooting follows the data path and eliminates layers.',m:'Continuing to investigate an upstream layer after evidence clears it.'},
{skill:'Communication',s:'A developer explains that the existing data model cannot represent a local fare rule cleanly.',q:'What is the strongest response?',a:['Tell them to make it work','Clarify the user/agency need, understand the model constraint and maintenance implications, then explore narrower product alternatives together','Remove the fare rule from scope without discussion','Ask for the database schema and redesign it yourself'],c:1,why:'Technical constraints are inputs to product judgment. Understand enough to reshape scope, not to become the database designer.',m:'Responding to technical constraints with either prescription or surrender.'},
{skill:'Analytics',s:'A funnel shows 80% of agencies enable a feature, but only 32% complete the first successful task.',q:'What is the most useful next cut?',a:['Company revenue','Drop-off by agency segment, onboarding path, error state and time-to-first-success','Average employee tenure','Number of roadmap items'],c:1,why:'The gap is between activation and first value. Segment that transition before deciding the feature lacks demand.',m:'Analyzing the wrong part of a funnel.'},
{skill:'Systems',s:'An issue occurs only after a new release and only for agencies using one configuration option.',q:'Which evidence would narrow the problem fastest?',a:['General rider satisfaction','Compare affected vs unaffected configurations before/after the release and identify what changed in that path','A new feature request survey','The agency contract value'],c:1,why:'Version and configuration are strong discriminators. Troubleshooting should exploit differences that isolate the failure path.',m:'Ignoring change/configuration boundaries during troubleshooting.'},
{skill:'Communication',s:'Data says a metric dropped 18%. Engineering says instrumentation changed in the same release.',q:'What should you do before escalating the product problem?',a:['Treat the 18% as true because the dashboard says so','Validate the event definition and measurement change, then distinguish real behaviour change from instrumentation change','Ask Design for a fix','Average it with last month'],c:1,why:'Measurement systems can fail too. Product decisions require confidence that the signal represents user behaviour.',m:'Treating analytics instrumentation as infallible.'},
{skill:'Partner work',s:'An agency asks for a firm delivery date before discovery has clarified the requirement.',q:'What is the strongest expectation-setting move?',a:['Give a conservative date now','Explain what must be resolved before a responsible estimate, give the next decision point, and separate discovery timing from delivery commitment','Avoid discussing timing','Promise the requested date and renegotiate later'],c:1,why:'Good partner management replaces false certainty with explicit dependencies and a useful next checkpoint.',m:'Turning uncertainty into an unsupported commitment.'},
{skill:'Judgment',s:'A feature request solves a real problem for one agency, but the same outcome could be achieved through a small workflow change on the agency side.',q:'What should influence the build decision?',a:['Software is always preferable','Frequency and severity of the problem, rider impact, agency burden, scalability, product strategy and whether the workaround is acceptable','Only engineering effort','Only agency size'],c:1,why:'A real problem does not automatically require a software feature. Compare the whole outcome and ongoing costs.',m:'Assuming every validated problem should become product scope.'},
{skill:'Delivery',s:'QA finds an edge case affecting 6% of journeys three days before launch.',q:'What is the first decision to make?',a:['Whether 6% sounds small','Whether the failure materially harms riders/partners, who is affected, whether it is recoverable, and whether mitigation or rollback exists','Whether the sprint is already closed','Whether the launch announcement is written'],c:1,why:'Release decisions are about consequence and recoverability, not percentage alone.',m:'Using prevalence without severity to make a release call.'},
{skill:'Problem framing',s:'An agency reports “riders hate the new experience.” Support shows 22 complaints, while completion increased 14%.',q:'What is the strongest interpretation?',a:['The complaints are wrong','The feature is successful because completion rose','The signals conflict; segment who is complaining, what changed in completion, and whether a minority is experiencing serious harm before deciding','Roll back immediately'],c:2,why:'Quantitative and qualitative evidence can point in different directions. Explain the difference instead of choosing the friendlier signal.',m:'Choosing one evidence type when signals conflict.'},
{skill:'Communication',s:'You need Engineering and Data to investigate a rider issue together.',q:'What makes the handoff effective?',a:['A long meeting with every stakeholder','A shared problem statement, affected population, examples, timeline, known/unknown facts, relevant metrics/log identifiers and the decision the investigation needs to enable','A preselected root cause','Separate messages with different descriptions'],c:1,why:'Cross-functional troubleshooting accelerates when everyone is solving the same precisely framed problem.',m:'Sending teams into an investigation without a shared frame.'}
);

// Override the rotation after the rest of the scripts load. This keeps the profile invisible but authoritative.
setTimeout(()=>{
  if(typeof ensureCycle==='function'){
    ensureCycle=function(force=false){const now=Date.now();if(force||!state.cycle||!state.nextRefresh||now>=state.nextRefresh){state.cycle=Math.floor(Math.random()*2147483646)+1;state.nextRefresh=now+(8+Math.random()*4)*3600000;save()}seed=state.cycle;rng=mulberry32(seed);quickSet=weightedQuickSet(quickBank,8,rng)};
    ensureCycle(false);
  }
  if(typeof startMixed==='function')startMixed=function(){const name=weightedModeName(rng);if(typeof window[name]==='function')window[name]()};
  if(typeof getInterviewSet==='function')getInterviewSet=function(level){const r=seededFor('interview-'+level.id);return weightedInterviewSet(level,r)};
},0);